### ISSUE TITLE
Videos not playing in Auvio - plugin 0.0.34

### ISSUE THREAD

**Issue by ze-big-ant** [zyphos/belgium-replay-tv#29]
Hello, for some days, I can't play Auvio's videos (version 0.0.33). I updated the plugin to 0.0.34 but it still doesn't work. Here is my log message:

```
2020-07-21 21:22:02.226 T:1494733536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.belgium/addon.py", line 82, in <module>
                                                sys.modules[channel_module_name].Channel(context)
                                              File "/home/osmc/.kodi/addons/plugin.video.belgium/channel.py", line 189, in __init__
                                                self.play_video(context)
                                              File "/home/osmc/.kodi/addons/plugin.video.belgium/rtbf.py", line 100, in play_video
                                                video_url = re.findall(media_regex, data)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```

Thank you in advance for your help.

**Comment by zyphos** [comment]
Fixed in version 0.0.35
RTBF has just introduced a new video quality of 1080p.
Do no forget to change preferred video quality in settings. (It falls back to a lower resolution if not available)

**Comment by ze-big-ant** [comment]
Wonderful! It works just fine. Thank you very much.
